// Extracted from Google Trends 2022 Wordwide
let suggestions = [
    "Wordle",
    "India vs England",
    "Ukraine",
    "Queen Elizabeth",
    "Ind vs SA",
    "World Cup",
    "India vs West Indies",
    "IPhone 14",
    "Jeffrey Dahmer",
    "Indian Premier League",
    "Queen Elizabeth passing",
    "Election results",
    "Powerball numbers",
    "Monkeypox",
    "Hurricane Ian",
    "Johnny Depp veredict",
    "Texas school shooting",
    "Will Smith Oscars",
    "Roe v Wade",
    "Johnny Depp",
    "Will Smith",
    "Amber Heard",
    "Vladimir Putin",
    "Chris Rock",
    "Novak Djokovic",
    "Anna Sorokin",
    "Andrew Tate",
    "Rishi Sunak",
    "Simon Leviev",
    "Jada Pinkett Smith",
    "Joseph Quinn",
    "Evan Peters",
    "Andrew Garfield",
    "Julia Fox",
    "Ezra Miller",
    "Rafael Nadal",
    "Serena Williams",
    "Manti Te'o",
    "Shaun White",
    "Yuzuru Hanyu",
    "Brittney Griner",
    "Gerard Pique",
    "Cain Velasquez",
    "Carlos Alcaraz",
    "India vs England",
    "Ind vs South Africa",
    "Ind vs Australia",
    "India vs Sri Lanka",
    "Pakistan vs England",
    "India vs Pakistan",
    "Zimbabwe vs India",
    "Bangladesh vs West Indies",
    "South Africa vs England",
    "Thor: Love and Thunder",
    "Black Adam",
    "Top Gun: Maverick",
    "The Batman",
    "Encanto",
    "Brahmastra: Part One - Shiva",
    "Jurassic World Dominion",
    "K.G.F: Chapter 2",
    "Uncharted",
    "Morbius",
    "Betty White",
    "Anne Heche",
    "Bob Saget",
    "Aaron Carter",
    "Panner pasanda",
    "Bolo caseiro",
    "Tuzlu kurabiye",
    "Overnight oats",
    "zimtschnecken",
    "Euphoria",
    "House of the Dragon",
    "Moon Knight",
    "The Watcher",
    "Inventing Arena",
    "Tak Ingin Usai - Keisya Levronka",
    "Pasoori - Ali Sethi and Shae Gill",
    "Glipse of Us - Joji",
    "Satru 2 - Denny Caknan and Happy Asmara",
    "Official Hige Dandism",
    "Ado",
    "As Is Was - Harry Styles",
    "Joko Tingkir - Farel Prayoga",
    "Habit - SEKAI NO OWARI",
    "Last Last - Burna Boy",
    "Butter - BTS",
    "Chaand Baaliyan - Aditya A",
    "Heat Waves - Glass Animals",
    "Enemy - Imagine Dragons",
    "Believer - Imagine Dragons",
    "Dynamite - BTS",
    "Ainsi bas la vida - Indila",
    "Everybody (Backstreet's Back) Backstreet Boys",
    "Srivalli - Javed Ali",
    "Olympic medal count",
    "flames",
    "Olympics",
    "CFL scores",
];